[workspace]
members = [ "crates/*" ]
exclude = [ "crates/argus_cli/tests/workspaces", "examples" ]
resolver = "2"

[patch.crates-io]
mdbook-preprocessor-utils = { path = "../mdbook-preprocessor-utils" }